all:
	gcc -Wall -Wextra -Werror ex00/*.c -o ex00/test
	./ex00/test
	gcc -Wall -Wextra -Werror ex01/*.c -o ex01/test
	./ex01/test
	gcc -Wall -Wextra -Werror ex02/*.c -o ex02/test
	./ex02/test
	gcc -Wall -Wextra -Werror ex03/*.c -o ex03/test
	./ex03/test
	gcc -Wall -Wextra -Werror ex04/*.c -o ex04/test
	./ex04/test
	gcc -Wall -Wextra -Werror ex05/*.c -o ex05/test
	./ex05/test
test00:
	gcc -Wall -Wextra -Werror ex00/*.c -o ex00/test
	./ex00/test
test01:
	gcc -Wall -Wextra -Werror ex01/*.c -o ex01/test
	./ex01/test test1 test2 test3
test02:
	gcc -Wall -Wextra -Werror ex02/*.c -o ex02/test
	./ex02/test test1 test2 test3
test03:
	gcc -Wall -Wextra -Werror ex03/*.c -o ex03/test
	./ex03/test sdfbds qdadf aweagd
test04:
	gcc -Wall -Wextra -Werror ex04/*.c -o ex04/test
	./ex04/test
test05:
	gcc -Wall -Wextra -Werror ex05/*.c -o ex05/test
	./ex05/test
test06:
	gcc -Wall -Wextra -Werror ex06/*.c -o ex06/test
	./ex06/test
test07:
	gcc -Wall -Wextra -Werror ex07/*.c -o ex07/test
	./ex07/test
norm:
	norminette */ft*.c