test00:
	gcc -Wall -Wextra -Werror ex00/*.c -o ex00/test
	./ex00/test
test01:
	gcc -Wall -Wextra -Werror ex01/*.c -o ex01/test
	./ex01/test
test02:
	gcc -Wall -Wextra -Werror ex02/*.c -o ex02/test
	./ex02/test
test03:
	gcc -Wall -Wextra -Werror ex03/*.c -o ex03/test
	./ex03/test
test04:
	gcc -Wall -Wextra -Werror ex04/*.c -o ex04/test
	./ex04/test
test05:
	gcc -Wall -Wextra -Werror ex05/*.c -o ex05/test
	./ex05/test
test06:
	gcc -Wall -Wextra -Werror ex06/*.c -o ex06/test
	./ex06/test
test07:
	gcc -Wall -Wextra -Werror ex07/*.c -o ex07/test
	./ex07/test
test08:
	gcc -Wall -Wextra -Werror ex08/*.c -o ex08/test
	./ex08/test
test09:
	gcc -Wall -Wextra -Werror ex09/*.c -o ex09/test
	./ex09/test
test10:
	gcc -Wall -Wextra -Werror ex10/*.c -o ex10/test
	./ex10/test
test11:
	gcc -Wall -Wextra -Werror ex11/*.c -o ex11/test
	./ex11/test
test12:
	gcc -Wall -Wextra -Werror ex12/*.c -o ex12/test
	./ex12/test
norm:
	norminette */ft*.c
