all:
	gcc -Wall -Wextra -Werror ex00/*.c -o ex00/test
	./ex00/test
	gcc -Wall -Wextra -Werror ex01/*.c -o ex01/test
	./ex01/test
	gcc -Wall -Wextra -Werror ex02/*.c -o ex02/test
	./ex02/test
	gcc -Wall -Wextra -Werror ex03/*.c -o ex03/test
	./ex03/test
	gcc -Wall -Wextra -Werror ex04/*.c -o ex04/test
	./ex04/test
	gcc -Wall -Wextra -Werror ex05/*.c -o ex05/test
	./ex05/test
test00:
	gcc -Wall -Wextra -Werror ex00/*.c -o ex00/test
	./ex00/test
test01:
	gcc -Wall -Wextra -Werror ex01/*.c -o ex01/test
	./ex01/test
test02:
	gcc -Wall -Wextra -Werror ex02/*.c -o ex02/test
	./ex02/test
test03:
	gcc -Wall -Wextra -Werror ex03/*.c -o ex03/test
	./ex03/test
test04:
	gcc -Wall -Wextra -Werror ex04/*.c -o ex04/test
	./ex04/test
test05:
	gcc -Wall -Wextra -Werror ex05/*.c -o ex05/test
	./ex05/test
norm:
	norminette */ft*.c