test00:
	gcc ex00/*.c -o ex00/test
	./ex00/test
test01:
	gcc ex01/*.c -o ex01/test
	./ex01/test
test02:
	gcc ex02/*.c -o ex02/test
	./ex02/test
test03:
	gcc ex03/*.c -o ex03/test
	./ex03/test
test04:
	gcc ex04/*.c -o ex04/test
	./ex04/test
test05:
	gcc ex05/*.c -o ex05/test
	./ex05/test
test06:
	gcc ex06/*.c -o ex06/test
	./ex06/test
test07:
	gcc ex07/*.c -o ex07/test
	./ex07/test
test08:
	gcc ex08/*.c -o ex08/test
	./ex08/test
norm:
	norminette */ft*.c
