test00:
	clang test_mains/main00.c ex00/ft_putchar.c -o test_00
	./test_00

test01:
	clang test_mains/main01.c ex01/ft_print_alphabet.c -o test_01
	./test_01

test02:
	clang test_mains/main02.c ex02/ft_print_reverse_alphabet.c -o test_02
	./test_02

test03:
	clang test_mains/main03.c ex03/ft_print_numbers.c -o test_03
	./test_03

test04:
	clang test_mains/main04.c ex04/ft_is_negative.c -o test_04
	./test_04

test05:
	clang test_mains/main05.c ex05/ft_print_comb.c -o test_05
	./test_05

test06:
	clang test_mains/main06.c ex06/ft_print_comb2.c -o test_06
	./test_06

test07:
	clang test_mains/main07.c ex07/ft_putnbr.c -o test_07
	./test_07

test08:
	clang test_mains/main08.c ex08/ft_print_combn.c -o test_08
	./test_08
